/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface __prefix__Child {
    }
    interface __prefix__Component {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTML__prefix__ChildElement extends Components.__prefix__Child, HTMLStencilElement {
    }
    var HTML__prefix__ChildElement: {
        prototype: HTML__prefix__ChildElement;
        new (): HTML__prefix__ChildElement;
    };
    interface HTML__prefix__ComponentElement extends Components.__prefix__Component, HTMLStencilElement {
    }
    var HTML__prefix__ComponentElement: {
        prototype: HTML__prefix__ComponentElement;
        new (): HTML__prefix__ComponentElement;
    };
    interface HTMLElementTagNameMap {
        "__prefix__-child": HTML__prefix__ChildElement;
        "__prefix__-component": HTML__prefix__ComponentElement;
    }
}
declare namespace LocalJSX {
    interface __prefix__Child {
    }
    interface __prefix__Component {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "__prefix__-child": __prefix__Child;
        "__prefix__-component": __prefix__Component;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "__prefix__-child": LocalJSX.__prefix__Child & JSXBase.HTMLAttributes<HTML__prefix__ChildElement>;
            "__prefix__-component": LocalJSX.__prefix__Component & JSXBase.HTMLAttributes<HTML__prefix__ComponentElement>;
        }
    }
}
